### ISSUE TITLE
Game crashing on third scene of the intro

### ISSUE THREAD

**Issue by silagarv** [UQcsse3200/2024-studio-3#668] opened 2024-10-17 03:21 UTC
## Description
Game crashes when attempting to get past thrid part of the intro cutscene.

## How To Reproduce
Steps to reproduce the behaviour:
1. Go to start
2. press no
3. enter until crashes

## Expected Behaviour
Shouldn't crash

## Temporary Fix
Skip cutscene

**Comment by Hayden-Elliott** [comment] 2024-10-17 03:26
at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.Stage.keyDown(Stage.java:418)
        at com.csse3200.game.input.InputDecorator.keyDown(InputDecorator.java:20)
        at com.csse3200.game.input.InputService.keyDown(InputService.java:82)
        at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:58)
        at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
        at com.csse3200.game.desktop.DesktopLauncher.main(DesktopLauncher.java:11)
Caused by: java.lang.IllegalArgumentException: key cannot be null.
        at com.badlogic.gdx.utils.ObjectMap.locateKey(ObjectMap.java:128)
        at com.badlogic.gdx.utils.ObjectMap.get(ObjectMap.java:177)
        at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:169)
        at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:143)
        at com.csse3200.game.services.ResourceService.getAsset(ResourceService.java:43)
        at com.csse3200.game.rendering.TextureRenderComponent.<init>(TextureRenderComponent.java:20)
        at com.csse3200.game.components.cutscenes.BackgroundRenderComponent.<init>(BackgroundRenderComponent.java:18)
        at com.csse3200.game.components.cutscenes.CutsceneFactory.createBackground(CutsceneFactory.java:32)
        at com.csse3200.game.components.cutscenes.Cutscene.createEntitiesForScene(Cutscene.java:227)
        at com.csse3200.game.components.cutscenes.Cutscene.loadScene(Cutscene.java:166)
        at com.csse3200.game.components.cutscenes.Cutscene.nextCutscene(Cutscene.java:120)
        at com.csse3200.game.components.cutscenes.Cutscene.setTextForScene(Cutscene.java:272)
        at com.csse3200.game.components.maingame.TextDisplay$1.keyDown(TextDisplay.java:344)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:53)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        ... 10 more
        
        
        Associated error path for continuity

**Comment by Hayden-Elliott** [comment] 2024-10-17 03:31
Error when creating BackgroundRenderComponent failing to initialise a RenderComponent

**Comment by Hayden-Elliott** [comment] 2024-10-17 03:35
Closed by #665

**Closed by Hayden-Elliott** 2024-10-17 03:35 UTC
Labels: bug, Team 5, Sprint 4
